# Generated by Django 3.1.5 on 2021-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210201_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('todo_items', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.ManyToManyField(blank=True, to='todolist.Category'),
        ),
    ]
