# Generated by Django 3.1.5 on 2021-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20210203_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=2, verbose_name='level')),
                ('tasks_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='todo_items',
            new_name='tasks_count',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
